apiVersion: v1
kind: Service
metadata:
  name: mongo1
  namespace: opencrvs
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo1
  namespace: opencrvs
spec:
  serviceName: mongo1
  replicas: 1
  selector:
    matchLabels:
      app: mongo1
  template:
    metadata:
      labels:
        app: mongo1
    spec:
      containers:
      - name: mongo1
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi