apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: opencrvs
spec:
  type: NodePort
  ports:
  - port: 4040
    targetPort: 4040
    nodePort: 30040
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      - name: private-key
        secret:
          secretName: opencrvs-private-key
      containers:
      - name: auth
        image: ghcr.io/opencrvs/ocrvs-auth:${VERSION}
        ports:
        - containerPort: 4040
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        - name: private-key
          mountPath: /secrets/private-key.pem
          subPath: private-key.pem
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: USER_MANAGEMENT_URL
          value: "http://user-mgnt:3030/"
        - name: CONFIG_TOKEN_EXPIRY_SECONDS
          value: "604800"
        - name: CONFIG_SMS_CODE_EXPIRY_SECONDS
          value: "600"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification:2020/"
        - name: METRICS_URL
          value: "http://metrics:1050"
        - name: COUNTRY_CONFIG_URL_INTERNAL
          value: "http://countryconfig:3040"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        - name: CERT_PRIVATE_KEY_PATH
          value: "/secrets/private-key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"