apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: opencrvs
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30000
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ghcr.io/opencrvs/ocrvs-client:${VERSION}
        ports:
        - containerPort: 80
        env:
        - name: COUNTRY_CONFIG_URL_INTERNAL
          value: "http://countryconfig:3040"
        - name: GATEWAY_URL_INTERNAL
          value: "http://gateway:7070"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"