apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: opencrvs
spec:
  type: NodePort
  ports:
  - port: 2021
    targetPort: 2021
    nodePort: 30021
  selector:
    app: config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      containers:
      - name: config
        image: ghcr.io/opencrvs/ocrvs-config:${VERSION}
        ports:
        - containerPort: 2021
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        env:
        - name: AUTH_URL
          value: "http://auth:4040"
        - name: COUNTRY_CONFIG_URL
          value: "http://countryconfig:3040"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "2021"
        - name: MONGO_URL
          value: "mongodb://mongo1/application-config"
        - name: SEARCH_URL
          value: "http://search:9090/"
        - name: METRICS_URL
          value: "http://metrics:1050"
        - name: USER_MANAGEMENT_URL
          value: "http://user-mgnt:3030/"
        - name: FHIR_URL
          value: "http://hearth:3447/fhir"
        - name: GATEWAY_URL
          value: "http://gateway:7070/"
        - name: DOCUMENTS_URL
          value: "http://documents:9050"
        - name: CHECK_INVALID_TOKEN
          value: "true"
        - name: HEARTH_MONGO_URL
          value: "mongodb://mongo1/hearth-dev"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"