apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: opencrvs
spec:
  type: NodePort
  ports:
  - port: 3020
    targetPort: 80
    nodePort: 30020
  selector:
    app: login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ghcr.io/opencrvs/ocrvs-login:${VERSION}
        ports:
        - containerPort: 80
        env:
        - name: COUNTRY_CONFIG_URL_INTERNAL
          value: "http://countryconfig:3040"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"