apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: opencrvs
spec:
  ports:
  - port: 1050
    targetPort: 1050
  selector:
    app: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      containers:
      - name: metrics
        image: ghcr.io/opencrvs/ocrvs-metrics:${VERSION}
        ports:
        - containerPort: 1050
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        env:
        - name: INFLUX_HOST
          value: "influxdb"
        - name: INFLUX_PORT
          value: "8086"
        - name: INFLUX_DB
          value: "ocrvs"
        - name: COUNTRY_CONFIG_URL
          value: "http://countryconfig:3040/"
        - name: CONFIG_API_URL
          value: "http://config:2021"
        - name: MONGO_URL
          value: "mongodb://mongo1/metrics"
        - name: HEARTH_MONGO_URL
          value: "mongodb://mongo1/hearth-dev"
        - name: DASHBOARD_MONGO_URL
          value: "mongodb://mongo1/performance"
        - name: SEARCH_URL
          value: "http://search:9090/"
        - name: USER_MANAGEMENT_URL
          value: "http://user-mgnt:3030"
        - name: DOCUMENTS_URL
          value: "http://documents:9050"
        - name: FHIR_URL
          value: "http://hearth:3447/fhir"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"