apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: opencrvs
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      containers:
      - name: search
        image: ghcr.io/opencrvs/ocrvs-search:${VERSION}
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        env:
        - name: HEARTH_MONGO_URL
          value: "mongodb://mongo1/hearth-dev"
        - name: NODE_ENV
          value: "development"
        - name: USER_MANAGEMENT_URL
          value: "http://user-mgnt:3030/"
        - name: ES_HOST
          value: "elasticsearch:9200"
        - name: FHIR_URL
          value: "http://hearth:3447/fhir"
        - name: APPLICATION_CONFIG_URL
          value: "http://config:2021/"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"