apiVersion: v1
kind: Service
metadata:
  name: user-mgnt
  namespace: opencrvs
spec:
  type: NodePort
  ports:
  - port: 3030
    targetPort: 3030
    nodePort: 30030
  selector:
    app: user-mgnt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mgnt
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mgnt
  template:
    metadata:
      labels:
        app: user-mgnt
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      containers:
      - name: user-mgnt
        image: ghcr.io/opencrvs/ocrvs-user-mgnt:${VERSION}
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        env:
        - name: MONGO_URL
          value: "mongodb://mongo1/user-mgnt"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification:2020/"
        - name: HOST
          value: "0.0.0.0"
        - name: METRICS_URL
          value: "http://metrics:1050"
        - name: FHIR_URL
          value: "http://hearth:3447/fhir"
        - name: APPLICATION_CONFIG_URL
          value: "http://config:2021/"
        - name: COUNTRY_CONFIG_URL
          value: "http://countryconfig:3040"
        - name: DOCUMENTS_URL
          value: "http://documents:9050"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"