apiVersion: v1
kind: Service
metadata:
  name: workflow
  namespace: opencrvs
spec:
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: workflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  namespace: opencrvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      volumes:
      - name: public-key
        secret:
          secretName: opencrvs-public-key
      containers:
      - name: workflow
        image: ghcr.io/opencrvs/ocrvs-workflow:${VERSION}
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: public-key
          mountPath: /secrets/public-key.pem
          subPath: public-key.pem
        env:
        - name: NODE_ENV
          value: "development"
        - name: SEARCH_URL
          value: "http://search:9090/"
        - name: METRICS_URL
          value: "http://metrics:1050"
        - name: DOCUMENTS_URL
          value: "http://documents:9050"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification:2020/"
        - name: USER_MANAGEMENT_URL
          value: "http://user-mgnt:3030/"
        - name: COUNTRY_CONFIG_URL
          value: "http://countryconfig:3040"
        - name: FHIR_URL
          value: "http://hearth:3447/fhir"
        - name: WEBHOOKS_URL
          value: "http://webhooks:2525/"
        - name: APPLICATION_CONFIG_URL
          value: "http://config:2021/"
        - name: AUTH_URL
          value: "http://auth:4040"
        - name: CERT_PUBLIC_KEY_PATH
          value: "/secrets/public-key.pem"
        - name: COUNTRY
          value: "${COUNTRY:-bgd}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"